[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags =
    -I src/domain/entities
    -I src/domain/repositories
    -I src/domain/services
    -I src/application/use_cases
    -I src/application/services
    -I src/infrastructure
    -I src/infrastructure/http
    -I src/infrastructure/json
    -I src/infrastructure/hardware
    -I src/interfaces/controllers
lib_deps =
    arduino-libraries/Arduino_JSON@^0.2.0
